export default function Head() {
  return (
    <>
      <title>Dewan Perwakilan Mahasiswa Keluarga Mahasiswa Universitas Muhammadiyah Purwokerto</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/icon_web_dpm.ico" />
    </>
  );
}
